# Generated by Django 4.2.9 on 2024-02-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
