# Generated by Django 4.2.9 on 2024-03-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, default='-', max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_number',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=11),
        ),
    ]
