# Generated by Django 4.2.5 on 2023-12-12 13:14

from django.db import migrations, models
import django.db.models.deletion
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('manager', models.CharField(blank=True, max_length=150)),
                ('manager_id', models.IntegerField(default=0)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=10)),
                ('date_update', models.CharField(blank=True, max_length=10)),
                ('date_closed', models.CharField(blank=True, max_length=10)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=10)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.tickets')),
            ],
        ),
    ]
