# Generated by Django 4.2.5 on 2023-12-12 15:47

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.CharField(default=jdatetime.datetime.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date_closed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date_update',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
