# Generated by Django 4.2.5 on 2023-12-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_tickets_date_alter_tickets_date_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerticket',
            name='type_user',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
