# Generated by Django 4.2.5 on 2023-12-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_answerticket_type_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerticket',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
