# Generated by Django 4.2.5 on 2023-12-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_rename_ticket_id_answerticket_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='date_closed',
        ),
    ]
