# Generated by Django 4.2.9 on 2024-02-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_address_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
