# Generated by Django 4.2.5 on 2023-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'blog categores',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('post_id', models.IntegerField(blank=True, default=0)),
                ('date', models.CharField(blank=True, max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('user', models.TextField(blank=True)),
                ('user_id', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dis_like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Comments For Posts ',
            },
        ),
        migrations.CreateModel(
            name='OpinionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.IntegerField(blank=True, default=0)),
                ('comment_id', models.IntegerField(blank=True, default=0)),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('user', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('category_id', models.IntegerField(blank=True, default=0)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('subcategory_id', models.IntegerField(blank=True, default=0)),
                ('image', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=10)),
                ('view', models.IntegerField(blank=True, default=0)),
                ('tags', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('usrer_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Post details',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('category_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'blog sub categores',
            },
        ),
    ]
