# Generated by Django 4.2.9 on 2024-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
            ],
        ),
    ]
