# Generated by Django 4.2.9 on 2024-03-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_scorepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScorePost',
        ),
    ]
