# Generated by Django 4.2.5 on 2023-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_website', models.CharField(blank=True, max_length=150)),
                ('title_panel', models.CharField(blank=True, max_length=150)),
                ('icon', models.ImageField(blank=True, upload_to='Main/icon/%y/%m/%d/')),
                ('logo', models.ImageField(blank=True, upload_to='Main/logo/%y/%m/%d/')),
                ('menu_name', models.TextField(blank=True)),
                ('menu_link', models.TextField(blank=True)),
            ],
        ),
    ]
