# Generated by Django 4.2.5 on 2023-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('copy_right', models.TextField(blank=True)),
                ('images', models.TextField(blank=True)),
                ('images_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, max_length=255)),
                ('cat_id', models.IntegerField(default=0)),
                ('title', models.TextField(blank=True)),
            ],
        ),
    ]
