# Generated by Django 4.2.5 on 2023-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_header_remove_mainmodel_menu_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True)),
            ],
        ),
    ]
