# Generated by Django 4.2.5 on 2023-12-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_emailshare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='Menu',
        ),
    ]
