# Generated by Django 4.2.5 on 2023-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_menu_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatfooter',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
