# Generated by Django 4.2.5 on 2023-12-21 10:19

from django.db import migrations, models
import django.db.models.deletion
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_subcatfooter_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=150)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('manager_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=150)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.chat')),
            ],
        ),
    ]
