# Generated by Django 4.2.5 on 2023-12-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_chat_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
