# Generated by Django 4.2.9 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_visit_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='roomname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
