# Generated by Django 4.2.9 on 2024-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_chat_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
