# Generated by Django 4.2.9 on 2024-01-27 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100)),
                ('ip_client', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('admin', models.CharField(blank=True, max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('client', 'client'), ('admin', 'admin')], max_length=25)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=150)),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Main.chatroom')),
            ],
        ),
    ]
