# Generated by Django 4.2.9 on 2024-01-27 14:29

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_chatroom_chatnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnew',
            name='date_active',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='date',
            field=models.CharField(default=jdatetime.datetime.now, max_length=150),
        ),
    ]
