# Generated by Django 4.2.9 on 2024-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_chatnew_date_active_alter_chatroom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnew',
            name='date_active',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
