# Generated by Django 4.2.9 on 2024-01-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_chatnew_date_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnew',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
