# Generated by Django 4.2.9 on 2024-01-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_chatnew_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
