# Generated by Django 4.2.9 on 2024-01-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_chatroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال'), ('اعلام نشده', 'اعلام نشده')], max_length=25),
        ),
    ]
