# Generated by Django 4.2.9 on 2024-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_alter_chatroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
