# Generated by Django 4.2.9 on 2024-01-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_footer_image_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='image_text',
            new_name='image1_text',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='images_url',
        ),
        migrations.AddField(
            model_name='footer',
            name='image1',
            field=models.ImageField(blank=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image2',
            field=models.ImageField(blank=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image2_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='footer',
            name='image3',
            field=models.ImageField(blank=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image3_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='footer',
            name='image4',
            field=models.ImageField(blank=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image4_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='footer',
            name='image5',
            field=models.ImageField(blank=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image5_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
