# Generated by Django 4.2.9 on 2024-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_rename_image_text_footer_image1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.FileField(blank=True, upload_to='Main/gif/%y/%m/%d/')),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
