# Generated by Django 4.2.9 on 2024-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_gif_slider_trend_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
