# Generated by Django 4.2.9 on 2024-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_trend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='link1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link5',
            field=models.TextField(blank=True),
        ),
    ]
