# Generated by Django 4.2.9 on 2024-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_footer_link1_footer_link2_footer_link3_footer_link4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, choices=[('بزرگ', 'بزرگ'), ('کوچک', 'کوچک')], max_length=50)),
            ],
        ),
    ]
