# Generated by Django 4.2.9 on 2024-03-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_delete_pictureindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='FAQ/ImageFAQ/%y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
