# Generated by Django 4.2.9 on 2024-03-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_test_text_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
