# Generated by Django 4.2.5 on 2023-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(blank=True, max_length=150)),
                ('group_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'product groups',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.TextField(blank=True)),
                ('name_product_english', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, max_length=150)),
                ('group_id', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('category_id', models.IntegerField(default=0)),
                ('sub_category', models.CharField(blank=True, max_length=150)),
                ('sub_category_id', models.IntegerField(default=0)),
                ('color', models.TextField(blank=True)),
                ('size', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='PanelProduct/ImageProduct/%y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='PanelProduct/ImageProduct/%y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='PanelProduct/ImageProduct/%y/%m/%d/')),
                ('image4', models.ImageField(blank=True, upload_to='PanelProduct/ImageProduct/%y/%m/%d/')),
                ('video', models.FileField(blank=True, upload_to='PanelProduct/VideoProduct/%y/%m/%d/')),
                ('attribute_title', models.TextField(blank=True)),
                ('attribute_value', models.TextField(blank=True)),
                ('title_text', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('discount_period', models.CharField(max_length=10)),
                ('discounted_price', models.FloatField(default=0)),
                ('instant_sale', models.BooleanField(default=False)),
                ('amazing_offer', models.BooleanField(default=False)),
                ('our_suggestion', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('sales_number', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('date', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(blank=True, max_length=150)),
                ('group_id', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('category_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product subcategories',
            },
        ),
    ]
