# Generated by Django 4.2.5 on 2023-12-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
