# Generated by Django 4.2.5 on 2023-12-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_text_product_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='description',
        ),
    ]
