# Generated by Django 4.2.5 on 2023-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_text_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_product', models.IntegerField(default=0)),
                ('build', models.IntegerField(default=0)),
                ('innovation', models.IntegerField(default=0)),
                ('ease_of_use', models.IntegerField(default=0)),
                ('designing', models.IntegerField(default=0)),
                ('possibilities', models.IntegerField(default=0)),
                ('worth', models.IntegerField(default=0)),
                ('buying', models.IntegerField(default=0)),
                ('title', models.TextField(blank=True)),
                ('Strengths', models.TextField(blank=True)),
                ('Weaknesses', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('tender', models.CharField(blank=True, max_length=75)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
