# Generated by Django 4.2.5 on 2023-12-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_commentsproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsproduct',
            old_name='Strengths',
            new_name='strengths',
        ),
        migrations.RenameField(
            model_name='commentsproduct',
            old_name='Weaknesses',
            new_name='weaknesses',
        ),
    ]
