# Generated by Django 4.2.5 on 2023-12-18 22:27

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_strengths_commentsproduct_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsproduct',
            name='date',
            field=models.CharField(default=jdatetime.datetime.now, max_length=50),
        ),
    ]
