# Generated by Django 4.2.9 on 2024-02-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_group_image_group_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
    ]
