# Generated by Django 4.2.9 on 2024-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_remove_group_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('address_id', models.IntegerField(default=0)),
                ('sending_method', models.IntegerField(default=0)),
                ('bill', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
    ]
