# Generated by Django 4.2.9 on 2024-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_productcart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
