# Generated by Django 4.2.9 on 2024-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_cart_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
    ]
