# Generated by Django 4.2.9 on 2024-02-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_favoriteproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='status',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
