# Generated by Django 4.2.9 on 2024-03-01 18:43

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_alter_favoriteproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.CharField(default=jdatetime.datetime.now, max_length=10),
        ),
    ]
