# Generated by Django 4.2.9 on 2024-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='preparation',
            field=models.BooleanField(default=False),
        ),
    ]
