# Generated by Django 4.2.9 on 2024-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_cart_cancel_cart_customer_cart_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
