# Generated by Django 4.2.9 on 2024-03-04 21:07

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_alter_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('user', models.CharField(blank=True, max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('date', models.CharField(default=jdatetime.datetime.now, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_date', models.CharField(default=jdatetime.datetime.now, max_length=50)),
                ('faq', models.BooleanField(default=False)),
            ],
        ),
    ]
