# Generated by Django 4.2.9 on 2024-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0025_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
