# Generated by Django 4.2.9 on 2024-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0026_question_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
