# Generated by Django 4.2.9 on 2024-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0030_alter_question_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
