# Generated by Django 4.2.9 on 2024-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0031_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_name_product',
            field=models.TextField(blank=True),
        ),
    ]
