# Generated by Django 4.2.9 on 2024-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0032_product_slug_name_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('user', models.CharField(blank=True, max_length=150)),
                ('star', models.IntegerField(default=0)),
            ],
        ),
    ]
