# Generated by Django 4.2.9 on 2024-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0033_starproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star_number',
            field=models.IntegerField(default=0),
        ),
    ]
