# Generated by Django 4.2.9 on 2024-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0034_product_star_product_star_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='starproduct',
            name='user_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
